#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Dec 10 15:13:54 2023

@author: alfie
"""
import numpy as np
from sympy import *

# Q1) a) Find roots of Equation 2
'''
c_m = 12
s_m = 1500

f = lambda x: x**4 + 2* c_m * x**3 + 3*s_m*x**2 + c_m* s_m *x + (s_m)**2

'''

x, y = symbols('x y') 

c_m = 12
s_m = 1500

f = lambda x: x**4 + 2* c_m * x**3 + 3*s_m*x**2 + c_m* s_m *x + (s_m)**2
'''
# solve the expression y (by default set equal to 0)
result = solve(y, x)

print((result[0]))'''

def roots(r, i, f):
    z_1 = r + i
    return f(z_1)



def brute_solve(N, M, f):
    roots_array = []
    while flag != 0:
        i = 0
        l = 0
                roots_array.append(roots(p, l, f))
    return roots_array

results = brute_solve(100, 100, f)

print(min(results))
            